show databases; 
use bzf9...c8r...vx5s; 
select database();
show tables;  
create table groups_names(group_id TINYINT(2), group_code varchar(5)); 
insert into groups_names(group_id, group_code) values(1, 'DP1-1'); 
select * from groups_names; 
insert into groups_names(group_id, group_code) values(1, 'DP1-2');
insert into groups_names(group_id, group_code) values(3, 'DP1-3'); 
insert into groups_names(group_id, group_code) values(4, 'DT1-1'); 
UPDATE groups_names SET group_id = 2 WHERE group_code = 'DP1-2'; 
select * from groups_names; 
SELECT group_id, group_code FROM groups_names; 
insert into groups_names(group_id, group_code) values(5, 'DT1-1'); 
insert into groups_names(group_id, group_code) values(5, 'DT1-2'); 
SELECT DISTINCT group_code FROM groups_names; 
SELECT group_id, group_code FROM groups_names ORDER BY group_id ASC; 
SELECT group_id, group_code FROM groups_names ORDER BY group_id DESC; 
SELECT group_id, group_code FROM groups_names WHERE group_code = 'DT1-1'; 
SELECT group_id, group_code FROM groups_names WHERE group_code = 'DT1-1' ORDER BY group_id DESC; 
SELECT group_id, group_code FROM groups_names WHERE group_id >= 2 AND group_id <= 4; 